name: Publish Packages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish cloudlayerio-dotnet
      uses: rohith/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: cloudlayerio-dotnet/cloudlayerio-dotnet.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
